---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alekssaul/demoapp-initializr-concourse
    tag: "v0.1.2"

inputs:
- name: si2ci

run:
  path: si2ci/pipeline/tasks/create-github-repo
