---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs

inputs:
- name: demoapp-initializr

#params:
  
run:
  path: demoapp-initializr/pipeline/tasks/create-github-repo
  