---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: demoapp-initializr

outputs:
- name: current-app-info

run:
  path: demoapp-initializr/pipeline/tasks/create-pas-space
