---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"
    
inputs:
- name: demoapp-initializr

run:
  path: demoapp-initializr/pipeline/tasks/push-templates
