groups:
- name: main
  jobs:
  - create-github-repo
  - push-templates
  - spring-initialize

resources:
- name: demoapp-initializr
  type: git
  source:
    branch: {{demo-initializr-branch}}
    uri: https://github.com/alekssaul/demoapp-initializr

jobs:
- name: create-github-repo
  serial: true
  public: true
  plan:
  - get: demoapp-initializr
    trigger: true
  - task: create-github-repo
    file: demoapp-initializr/pipeline/tasks/create-github-repo.yml
    params:
      DEMOAPP_INITIALIZR_GITHUBTOKEN: {{GITHUBTOKEN}}
      REPONAME: {{REPONAME}} 

- name: push-templates
  serial: true
  public: true
  plan:
  - get: demoapp-initializr
    trigger: true
    passed:
      - create-github-repo
  - task: commit-templates
    file: demoapp-initializr/pipeline/tasks/push-templates.yml
    params:
      DEMOAPP_INITIALIZR_GITHUBTOKEN: {{GITHUBTOKEN}}
      REPONAME: {{REPONAME}} 
      GITHUBORGNAME: {{GITHUBORGNAME}}
      GITHUBSSHKEY: {{GITHUBSSHKEY}}

- name: spring-initialize
  serial: true
  public: true
  plan:
  - get: demoapp-initializr
    trigger: true
    passed:
      - push-templates
  - task: spring-initialize
    file: demoapp-initializr/pipeline/tasks/spring-initialize.yml
    params:
      DEMOAPP_INITIALIZR_GITHUBTOKEN: {{GITHUBTOKEN}}
      REPONAME: {{REPONAME}} 
      GITHUBORGNAME: {{GITHUBORGNAME}}
      GITHUBSSHKEY: {{GITHUBSSHKEY}}
      SPRINGINITURL: {{SPRINGINITURL}}

    