groups:
- name: main
  jobs:
  - create-github-repo
  - push-templates
  - spring-initialize
  - create-app-pipeline
  - prepare-PCF

resources:
- name: demoapp-initializr
  type: git
  source:
    branch: {{demo-initializr-branch}}
    uri: https://github.com/alekssaul/demoapp-initializr

jobs:
- name: create-github-repo
  serial: true
  public: true
  plan:
  - get: demoapp-initializr
    trigger: true
  - task: create-github-repo
    file: demoapp-initializr/pipeline/tasks/create-github-repo.yml
    params:
      DEMOAPP_INITIALIZR_GITHUBTOKEN: {{GITHUBTOKEN}}
      REPONAME: {{REPONAME}} 

- name: push-templates
  serial: true
  public: true
  plan:
  - get: demoapp-initializr
    trigger: true
    passed:
      - create-github-repo
  - task: commit-templates
    file: demoapp-initializr/pipeline/tasks/push-templates.yml
    params:
      DEMOAPP_INITIALIZR_GITHUBTOKEN: {{GITHUBTOKEN}}
      REPONAME: {{REPONAME}} 
      GITHUBORGNAME: {{GITHUBORGNAME}}
      GITHUBSSHKEY: {{GITHUBSSHKEY}}

- name: spring-initialize
  serial: true
  public: true
  plan:
  - get: demoapp-initializr
    trigger: true
    passed:
      - push-templates
  - task: spring-initialize
    file: demoapp-initializr/pipeline/tasks/spring-initialize.yml
    params:
      DEMOAPP_INITIALIZR_GITHUBTOKEN: {{GITHUBTOKEN}}
      REPONAME: {{REPONAME}} 
      GITHUBORGNAME: {{GITHUBORGNAME}}
      GITHUBSSHKEY: {{GITHUBSSHKEY}}
      SPRINGINITURL: {{SPRINGINITURL}}
  - task: create-mockcode
    file: demoapp-initializr/pipeline/tasks/create-mockcode.yml
    params:
      DEMOAPP_INITIALIZR_GITHUBTOKEN: {{GITHUBTOKEN}}
      REPONAME: {{REPONAME}} 
      GITHUBORGNAME: {{GITHUBORGNAME}}
      GITHUBSSHKEY: {{GITHUBSSHKEY}}
- name: prepare-PCF
  serial: true
  public: true
  plan:
  - get: demoapp-initializr
    trigger: true
    passed:
      - spring-initialize
  - task: create-pas-space
    file: demoapp-initializr/pipeline/tasks/create-pas-space.yml
    params:
      DEMOAPP_INITIALIZR_GITHUBTOKEN: {{GITHUBTOKEN}}
      REPONAME: {{REPONAME}} 
      GITHUBORGNAME: {{GITHUBORGNAME}}
      GITHUBSSHKEY: {{GITHUBSSHKEY}}
      SPRINGINITURL: {{SPRINGINITURL}}
      CONCOURSEURL: {{CONCOURSEURL}}
      GIT_URL: {{GIT_URL}}
      DEPLOY_USERNAME: {{DEPLOY_USERNAME}}
      DEPLOY_PASSWORD: {{DEPLOY_PASSWORD}}
      PAS_ORGANIZATION: {{PAS_ORGANIZATION}}
      PAS_SPACE: {{PAS_SPACE}}
      PAS_API: {{PAS_API}}
      PAS_APP_SUFFIX: {{REPONAME}}
      PAS_DOMAIN: {{PAS_DOMAIN}}
      CONCOURSE_USERNAME: {{CONCOURSE_USERNAME}}
      CONCOURSE_PASSWORD: {{CONCOURSE_PASSWORD}}


- name: create-app-pipeline
  serial: true
  public: true
  plan:
  - get: demoapp-initializr
    trigger: true
    passed:
      - prepare-PCF
  - task: create-app-pipeline
    file: demoapp-initializr/pipeline/tasks/create-app-pipeline.yml
    params:
      DEMOAPP_INITIALIZR_GITHUBTOKEN: {{GITHUBTOKEN}}
      REPONAME: {{REPONAME}} 
      GITHUBORGNAME: {{GITHUBORGNAME}}
      GITHUBSSHKEY: {{GITHUBSSHKEY}}
      SPRINGINITURL: {{SPRINGINITURL}}
      CONCOURSEURL: {{CONCOURSEURL}}
      GIT_URL: {{GIT_URL}}
      DEPLOY_USERNAME: {{DEPLOY_USERNAME}}
      DEPLOY_PASSWORD: {{DEPLOY_PASSWORD}}
      PAS_ORGANIZATION: {{PAS_ORGANIZATION}}
      PAS_SPACE: {{PAS_SPACE}}
      PAS_API: {{PAS_API}}
      PAS_APP_SUFFIX: {{REPONAME}}
      PAS_DOMAIN: {{PAS_DOMAIN}}
      CONCOURSE_USERNAME: {{CONCOURSE_USERNAME}}
      CONCOURSE_PASSWORD: {{CONCOURSE_PASSWORD}}
